# -*- coding: utf-8 -*-
"""manipulasi data2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Q8VFzxq6wi1TlSh8KztyCE1rmqKliyb
"""

template = 'Halo, saya %s dari %s'

print(template %('lendis febri', 'indonesia'))

template = 'halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'

print(template.format(nama = 'latifa', asal = 'unila'))
print(template_2.format('nasi goreng', 'air putih'))

nama = 'lendis febri'
asal = 'indonesia'

print(f'perkenalkan saya {nama} dari {asal}')

"""split data"""

alamat = 'surabaya, jawa timur, indonesia'

print(alamat.split())
print(alamat.split('.'))
print(alamat.split('. '))

"""join data"""

print(' '.join(['aku', 'suka', 'phyton']))

"""huruf kapital dan lowe"""

print('halo selamat pagi'.upper())
print('halo selamat siang'.upper())
print('APA KABAR'.lower())
print('lagi dimana?'.lower())

print('daun tidak pernah membenci angin'.title())

"""swapcasae"""

print('indonesia Adalah Negara kepulauan'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

angka = '12345'
print('indeks angtka 3:', angka.find('3'))
print('indeks angtka 45:', angka.find('45'))
print('indeks angtka 35:', angka.find('35'))

ibu_kota = 'jakarta'
print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', ''))
print(ibu_kota.replace('a', ''))

"""menghitung jumlah karakter"""

paragraf = 'baru-barunini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'kata "di" muncul sebanyak {x} kali')

