# -*- coding: utf-8 -*-
"""manipulasi String

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1353n94OcOynR96fVqNpRt_42ReAXLqYo

operasi pada string
"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan\
teks editor masa kini seperti Visual Code, \
atom. sublime text, dan lain sebagainya.'
print('sublime text' in berita)
print('notepad++' in berita)

"""memotong string"""

nama = 'Landis Fabri'
print(nama[4])
print(nama[7])
print(nama[-1])
print(nama[-3])

"""slicing string"""

judul = 'pelajaran matematika untuk SD'
print(judul[0:5])
print(judul[10])
print(judul[10:15])
print(judul[-1:-3])
print(judul[:-3])
print(judul[-5:])

"""menghitung panjang string"""

print(len('indonesia'))
print(len('malaysia'))

"""memeriksa karakter awal"""

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '6288776655300'
nomor_telepon_3 = '+6233003300330'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

"""memeriksa karakter string"""

email_1 = 'presiden@gmail.com'
email_2 = 'president@out look.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gmail.com'))