# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wX6TF-rQMu73HbjUHygY2OJDOhRqrH5B
"""

nama= latifatul qouliyah
npm= 2411012064

"""STRING"""

nama = "latifatul qouliyah"
asal = "indonesia"

print(nama)
print(asal)
print(nama + asal)
print("halo, nama saya", nama, "asal saya dari", asal)

data_lengkap = (nama+asal)
print(data_lengkap)

"""STRING + NON STRING"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

print(asal_kota)